const seasonStart = new Date('2026-08-01T10:30:00');
const startWeightLb = 15*14+10;
const targetWeightLb = 14*14;
const storeKey='seasonReadyV1';
const defaultData={logs:[], body:[], completed:{}, settings:{level:'Base', pain:0, energy:7}};
let data=JSON.parse(localStorage.getItem(storeKey)||JSON.stringify(defaultData));
function save(){localStorage.setItem(storeKey,JSON.stringify(data)); renderAll();}
function stlb(lb){const st=Math.floor(lb/14), l=Math.round(lb-st*14); return `${st}st ${l}lb`;}
function todayKey(){return new Date().toISOString().slice(0,10)}
function dayName(){return new Date().toLocaleDateString('en-GB',{weekday:'long'})}
function daysLeft(){return Math.max(0,Math.ceil((seasonStart-new Date())/86400000));}
const plans={
Monday:{title:'Gym: Upper body + Zone 2', focus:'Build muscle, protect joints, improve fat loss base', gym:[['Chest press or DB press','3','8-12'],['Seated row','3','10-12'],['Lat pulldown','3','10-12'],['Shoulder press machine','2','8-10'],['Cable face pulls','3','12-15'],['Biceps curl','2','10-12'],['Triceps rope pushdown','2','10-12'],['Bike/treadmill incline walk','20 min','steady']], football:[]},
Tuesday:{title:'Football: Ball mastery + conditioning', focus:'First touch, turns, repeated efforts', gym:[], football:[['Cone dribble slalom','6 rounds','controlled'],['Wall passing both feet','5 x 2 min','one/two touch'],['First touch out of feet','5 x 90 sec','alternate feet'],['Shuttle runs 10-20-30m','6 rounds','walk back recovery']]},
Wednesday:{title:'Gym: Lower body strength', focus:'Leg strength for sprinting and shielding the ball', gym:[['Leg press','4','8-12'],['Romanian deadlift','3','8-10'],['Walking lunges','3','10 each leg'],['Hamstring curl','3','10-12'],['Calf raises','3','12-15'],['Plank','3','30-60 sec'],['Easy bike cooldown','10 min','easy']], football:[]},
Thursday:{title:'Football: Tempo fitness + skills', focus:'Central midfield engine and striker sharpness', gym:[], football:[['Ball mastery box touches','5 x 90 sec','quick feet'],['Wall passing weak foot','5 x 90 sec','quality reps'],['30 sec fast / 60 sec easy runs','10 rounds','RPE 7'],['Finishing movement practice','10 min','open body, check shoulder']]},
Friday:{title:'Gym: Full body + intervals', focus:'Match power without ruining Saturday legs', gym:[['Goblet squat','3','10'],['Incline DB press','3','8-10'],['Cable row','3','10-12'],['Hip thrust or glute bridge','3','10-12'],['Pallof press','3','10 each side'],['Assault bike/rower intervals','8 x 30 sec','60 sec easy']], football:[]},
Saturday:{title:'Match day / match fitness', focus:'80-minute game at 10.30am once season starts', gym:[], football:[['Warm-up mobility','10 min','hips, calves, hamstrings'],['Match or park run','80 min','controlled effort'],['Post-session stretch','10 min','recovery']]},
Sunday:{title:'Recovery + weekly check-in', focus:'Weigh-in, mobility and plan adjustment', gym:[['Easy walk or bike','30-45 min','easy'],['Mobility','15 min','hips/ankles/back']], football:[]}
};
function adaptiveAdvice(){const recent=data.logs.slice(-7); const avgEnergy=recent.length?recent.reduce((a,b)=>a+(+b.energy||7),0)/recent.length:7; const avgPain=recent.length?recent.reduce((a,b)=>a+(+b.pain||0),0)/recent.length:0; const done=recent.filter(l=>l.complete).length; let level='Base', advice='Stay consistent. Complete the planned sessions before adding more.'; if(avgPain>=6||avgEnergy<=4){level='Recovery'; advice='Back off today: reduce weights by 10–20%, keep cardio easy, focus on movement quality.'} else if(done>=5&&avgEnergy>=7&&avgPain<=3){level='Build'; advice='You are coping well. Add one extra set to main lifts or one extra conditioning round.'} else if(done>=6&&avgEnergy>=8&&avgPain<=2){level='Peak'; advice='Peak week: sharper sprint work, but keep one full recovery day.'} data.settings.level=level; return {level,advice,done,avgEnergy:avgEnergy.toFixed(1),avgPain:avgPain.toFixed(1)} }
function renderToday(){const p=plans[dayName()]||plans.Monday; const key=todayKey(); const a=adaptiveAdvice(); const items=[...p.gym.map(x=>({type:'Gym',x})),...p.football.map(x=>({type:'Football',x}))]; document.getElementById('today').innerHTML=`<section class="card"><p class="eyebrow">${dayName()}</p><h2>${p.title}</h2><p class="muted">${p.focus}</p><p class="pill">Adaptive level: ${a.level}</p><p class="notice">${a.advice}</p></section><section class="card"><h2>Session</h2>${items.map((it,i)=>`<div class="task ${data.completed[key+'-'+i]?'complete':''}"><h3>${it.x[0]}</h3><p class="muted">${it.type} • ${it.x[1]} • ${it.x[2]}</p><div class="setgrid"><input id="w${i}" placeholder="Weight"><input id="r${i}" placeholder="Reps"><select id="e${i}"><option>Right</option><option>Easy</option><option>Hard</option></select></div><button class="primary mini" onclick="completeTask(${i})">Complete</button></div>`).join('')||'<p>Recovery/check-in day. Keep it easy.</p>'}<div class="row"><div><label>Energy 1-10</label><input id="energy" type="number" min="1" max="10" value="7"></div><div><label>Pain 0-10</label><input id="pain" type="number" min="0" max="10" value="0"></div></div><label>Notes</label><textarea id="notes" placeholder="How did it feel?"></textarea><button class="bigbtn primary" onclick="saveSession()">Save today</button></section>`}
window.completeTask=(i)=>{data.completed[todayKey()+'-'+i]=true; save();}
window.saveSession=()=>{data.logs.push({date:todayKey(),day:dayName(),complete:true,energy:document.getElementById('energy').value,pain:document.getElementById('pain').value,notes:document.getElementById('notes').value}); save();}
function renderPlan(){document.getElementById('plan').innerHTML=`<section class="card"><h2>Weekly plan</h2>${Object.entries(plans).map(([d,p])=>`<div class="task"><h3>${d}: ${p.title}</h3><p class="muted">${p.focus}</p>${p.gym.length?'<span class="pill">Gym</span>':''}${p.football.length?'<span class="pill">Football</span>':''}</div>`).join('')}</section><p class="footerNote">When team training starts, replace Thursday football conditioning with team training and keep Friday lighter.</p>`}
function renderLog(){document.getElementById('log').innerHTML=`<section class="card"><h2>Body check-in</h2><div class="row"><div><label>Weight</label><input id="bodyWeight" placeholder="e.g. 15st 8lb or 218"></div><div><label>Waist cm</label><input id="waist" type="number"></div></div><label>Body comp notes</label><textarea id="bodyNotes" placeholder="Photos, clothes fit, energy, soreness"></textarea><button class="bigbtn secondary" onclick="saveBody()">Save check-in</button></section><section class="card"><h2>Recent sessions</h2>${data.logs.slice(-10).reverse().map(l=>`<div class="task"><strong>${l.date} - ${l.day}</strong><p class="muted">Energy ${l.energy}/10 • Pain ${l.pain}/10</p><p>${l.notes||''}</p></div>`).join('')||'<p>No sessions logged yet.</p>'}</section>`}
window.saveBody=()=>{data.body.push({date:todayKey(),weight:document.getElementById('bodyWeight').value,waist:document.getElementById('waist').value,notes:document.getElementById('bodyNotes').value}); save();}
function renderProgress(){const a=adaptiveAdvice(); const latest=data.body[data.body.length-1]; let weightText=latest?.weight||'No weight logged yet'; document.getElementById('progress').innerHTML=`<section class="card"><h2>Progress</h2><p>Latest weight: <strong>${weightText}</strong></p><p>Target: <strong>${stlb(targetWeightLb)}</strong></p><div class="bar"><span style="width:${Math.min(100,(a.done/6)*100)}%"></span></div><p class="muted">Sessions completed in recent log: ${a.done}/6</p><p class="pill">Avg energy ${a.avgEnergy}</p><p class="pill">Avg pain ${a.avgPain}</p><p class="pill">Level ${a.level}</p></section><section class="card"><h2>Weight/body log</h2>${data.body.slice(-12).reverse().map(b=>`<div class="task"><strong>${b.date}</strong><p class="muted">Weight: ${b.weight||'-'} • Waist: ${b.waist||'-'}cm</p><p>${b.notes||''}</p></div>`).join('')||'<p>No body check-ins yet.</p>'}</section>`}
function renderAll(){document.getElementById('todayTitle').textContent=dayName(); document.getElementById('countdown').textContent=`${daysLeft()} days until August pre-season target`; const logs=data.logs.slice(-7); const score=Math.max(1,Math.min(100,50+logs.filter(l=>l.complete).length*6-(logs.reduce((a,b)=>a+(+b.pain||0),0)*1.5))); document.getElementById('fitnessScore').textContent=Math.round(score); renderToday(); renderPlan(); renderLog(); renderProgress();}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active')); b.classList.add('active'); document.getElementById(b.dataset.view).classList.add('active')});
document.getElementById('resetBtn').onclick=()=>{if(confirm('Clear all saved Season Ready data?')){localStorage.removeItem(storeKey); data=JSON.parse(JSON.stringify(defaultData)); renderAll();}}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{});} renderAll();
